Repository MinervaScompany/obd-utils, pull requests merged in 2023-10, with the labels that each got.

#13 rename pid pressure
  src/obdInfo.ts
Labels: enhancement, patch

#16 Refactor: change pid name
  .gitignore
  .npmignore
  src/obdInfo.ts
Labels: enhancement, patch

#19 Fix/multipid
  bin/scripts/cli.js
  scripts/cli.ts
  src/index.ts
  src/obdInfo.ts
Labels: enhancement, minor

#21 fix: rename iat PID to temperature
  src/obdInfo.ts
Labels: enhancement, patch

#22 fix: rename ait
  src/obdInfo.ts
Labels: documentation, patch
