Repository MinervaScompany/obd-utils, pull requests merged in 2023-05, with the labels that each got.

#1 First PR
  README.md
  package-lock.json
  src/obdInfo.ts
  src/obdTypes.ts
Labels: enhancement

#2 Feat: add workflows and fix errors with eslint
  .eslintrc.cjs
  .github/workflows/pr-label.yml
  .github/workflows/pr-open.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .prettierrc.js
  bin/scripts/cli.js
  package-lock.json
  package.json
  scripts/cli.ts
  scripts/generate-pid-readme.ts
  src/index.ts
  src/obdInfo.ts
  src/obdTypes.ts
Labels: documentation, patch

#3 Publish patch to npm
  .github/workflows/pr-open.yml
  .github/workflows/publish.yml
Labels: patch

#5 chore: try to publish to npm
  .github/workflows/pr-close.yml
Labels: patch

#7 Fix: Use index of es6 module
  package.json
Labels: bug, patch
